# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "dev-app"
client_id = "b7b4ad6bf46287cf8049270cad0a39a8"
application_url = "https://stainless-gibraltar-nw-claimed.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://stainless-gibraltar-nw-claimed.trycloudflare.com/auth/callback",
  "https://stainless-gibraltar-nw-claimed.trycloudflare.com/auth/shopify/callback",
  "https://stainless-gibraltar-nw-claimed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "functions-checkout.myshopify.com"
