api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "donations-dev"
handle = "donations-dev"

[[extensions.targeting]]
module = "./src/Checkout.js"
target = "Checkout::Dynamic::Render"

[extensions.capabilities]
api_access = true
# network_access = true

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"


# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"
