api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "custom-banner"
handle = "custom-banner"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/Checkout.js"

[extensions.capabilities]
api_access = true
network_access = true

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"


[extensions.settings]
  [[extensions.settings.fields]]
  key = "title"
  type = "single_line_text_field"
  name = "Banner title"
  description = "Enter a title for the banner."

  [[extensions.settings.fields]]
  key = "description"
  type = "single_line_text_field"
  name = "Banner description"
  description = "Enter a description for the banner."

  [[extensions.settings.fields]]
  key = "status"
  type = "single_line_text_field"
  name = "Banner status"

    [[extensions.settings.fields.validations]]
    name = "choices"
    value = "[\"info\", \"success\", \"warning\", \"critical\"]"

  [[extensions.settings.fields]]
  key = "collapsible"
  type = "boolean"
  name = "Show collapsible description."
  description = "Display controls to expand or collapse the banner description."
