api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "client-validation"
handle = "client-validation"

[[extensions.targeting]]
module = "./src/Checkout.js"
target = "purchase.checkout.contact.render-after"

[extensions.capabilities]
api_access = true
network_access = true
block_progress = true



# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"


[extensions.settings]

[[extensions.settings.fields]]
key = "boolean"
type = "boolean"
name = "True or false"
description = "Pick one"

[[extensions.settings.fields]]
key = "banner_title"
type = "single_line_text_field"
name = "Banner title"
description = "Enter a title for the banner"

[[extensions.settings.fields.validations]]
name = "choices"
value = "[\"info\", \"success\", \"warning\", \"critical\"]"


[[extensions.settings.fields]]
key = "variant_ref_1"
type = "variant_reference"
name = "$1 Donation variant"
description = "Enter a variant number for the product"

[[extensions.settings.fields]]
key = "variant_ref_5"
type = "variant_reference"
name = "$5 Donation variant"
description = "Enter a variant number for the product"

[[extensions.settings.fields]]
key = "variant_ref_10"
type = "variant_reference"
name = "$10 Donation variant"
description = "Enter a variant number for the product"

[[extensions.settings.fields]]
key = "date_field"
type = "date"
name = "Date picker"
description = "Choose a date for ?"